### PR TITLE
fix(objc): call emitMessageToRN method not property

### PR DESCRIPTION
**Pull request by bduyng**

### CODE REVIEW

**Comment by bduyng** [comment]
@peggyrayzis You are welcome!! Thanks for your amazing work. 🍻

**Comment by peggyrayzis** [comment]
I just cut a new release with your change to the template 😀 

Next time, it would be a huge help if you could please update the Jest snapshot tests! You can run `npm run test:update` to update the template snapshot. Then, you can commit the new snapshot along with your fix.

I'm going to be refining the contribution process over the next few weeks to include PR templates, CI, and code review automation to better communicate this to everyone.

Thanks again @bduyng & welcome to RNCB! 🎉 🍻

**Comment by bduyng** [comment]
Awesome!!! Can't wait to contribute more to this project and React Native community! I am working on #15 btw :)

**Comment by peggyrayzis** [comment]
Wow thank you!! I was going to tackle this earlier this week but got sidetracked so I'm glad you're working on it 😀 

Let me know if you run into any issues or have any questions along the way. I'm happy to pair if you get stuck!

**Comment by bduyng** [comment]
Yes sure will let you know if I need any help. Thanks again @peggyrayzis!!

**Pull request merged**
