### PR TITLE
fix(android): update templates & tests to fix RN v0.47.2 breaking change

### PR DESCRIPTION
**Pull request by peggyrayzis**
## How:
- Check RN version from `package.json`
- Override `createJSModules` in Android & Kotlin templates for the package if version is below v0.47.2
- Take out `createJSModules` override if version is latest or above
- Updated `readAndWriteFiles` & `parseFile` functions to take a config option as second param
- Updated Jest tests

## Checklist:

- [x] I read the [contributor guidelines](https://github.com/peggyrayzis/react-native-create-bridge/blob/master/CONTRIBUTING.md)
- [x] My commit messages & PR title follow [Conventional Changelog Standard](https://github.com/peggyrayzis/react-native-create-bridge/blob/master/CONTRIBUTING.md#how-should-i-format-my-commit-messages)
- [x] I added tests for my new feature
- [  ] I added documentation for my new feature

### CODE REVIEW

**Comment by peggyrayzis** [comment]
Thanks for pointing out that I needed to do the version check, @andrerfneves! Would you like to give this a review? 😀

**Comment by andrerfneves** [comment]
Looks really good @peggyrayzis. The only thing I'd note is that this check `if (rnVersion < "0.47.2")` may not always return correctly. Say you have other chars like `^` or `+` in your `react-native` package dependency delcaration in `package.json`?

Maybe your `parseFile` function already takes care of that? Haven't gotten the chance to read through all the source code. 

Otherwise, 👍

**Comment by andrerfneves** [comment]
More info here too: https://github.com/facebook/react-native/issues/15232

**Comment by peggyrayzis** [comment]
Nope it doesn't take care of that, good catch! I'm going to use an npm package `compare-versions` to check the versions so I don't have to write the parsing logic myself :) thanks again for reviewing!

**Pull request merged**
